### PR TITLE
Allow bastion_instance_count to be set to 0

### LINKED ISSUE #46: Allow deploys without bastion host
(make sure to not reserve the EIP in that case)

### PR DESCRIPTION
**Pull request by DeviaVir**
set:
```
region: { bastion_instance_count: 0 }
```

Fixes #46

### CODE REVIEW

**Comment by DeviaVir** [comment]
CloudFormation be like
screen shot 2016-11-10 at 17 23 13

**Comment by DeviaVir** [comment]
@thepwagner off-topic, jenkins tests are way different than local tests (looks like I poked a few holes that I'll need to fix), I think we had this with `GDH` too at some point, remember what we did about that?

**Comment by thepwagner** [comment]
@DeviaVir iirc that was an issue with `.coverage` being cached between runs; shouldn't(?) be an issue since tests are run in fresh containers?

**Comment by DeviaVir** [comment]
@thepwagner fresh tests!

**Pull request merged**
